In [1]:
#Numpy crash course
import numpy as np 

In [2]:
#NumpyArray
mylist = [1,2,3]
nparray = np.array(mylist)
print(nparray)

[1 2 3]


In [5]:
#2D array
mylist = [[1,2,3] , [4,5,6], [2,3]]
nparray = np.array(mylist)
print(nparray)

[list([1, 2, 3]) list([4, 5, 6]) list([2, 3])]


In [6]:
#Range function
nparray = np.arange(0,10,2)
print(nparray)

[0 2 4 6 8]


In [64]:
#Zeroes function
nparray = np.zeros(2)
print(nparray)

[0. 0.]


In [65]:
#Zeroes function 2d
nparray = np.zeros((3,2))
print(nparray)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
#Ones function
nparray = np.ones((3,2))
print(nparray)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
#Ones function 2d
nparray = np.linspace(1,10,3)
print(nparray)

[ 1.   5.5 10. ]


In [13]:
#Identity matrix
nparray = np.eye(5)
print(nparray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [67]:
#Rand numbers 0-1
nparray = np.random.rand(3,4)
print(nparray)

[[0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]]


In [16]:
#Random std normal dist
nparray = np.random.randn(3,4)
print(nparray)

[[ 1.32081249 -0.47720026 -2.0845742   1.28413071]
 [ 0.7874638   0.14861116 -0.62943884 -1.27941083]
 [-0.13638072 -1.6652145  -0.40291562  0.41014898]]


In [19]:
#Rand int in low-high range
nparray = np.random.randint(3,10,5)
print(nparray)

[6 4 5 4 7]


In [20]:
nparray = np.random.randint(3,10,(2,2))
print(nparray)

[[7 7]
 [3 3]]


In [22]:
#Seed
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
#Reshape
nparray = np.arange(25)
nparray.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
nparray.max()

24

In [26]:
nparray.argmax()

24

In [27]:
nparray = np.arange(0,10)
nparray[1]

1

In [28]:
nparray[1:3]

array([1, 2])

In [29]:
#Broadcasting
nparray[1:5] =100
print(nparray)

[  0 100 100 100 100   5   6   7   8   9]


In [30]:
nparray[:] =100
print(nparray)

[100 100 100 100 100 100 100 100 100 100]


In [38]:
nparray = np.array([[1,2,3],[4,5,6],[7,8,9]])
nparray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
nparray[2]

array([7, 8, 9])

In [40]:
#Slicing
nparray[1:2,2:3]

array([[6]])

In [41]:
#Filter
nparray > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [42]:
boolarray = nparray>4
boolarray

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [43]:
nparray[boolarray]

array([5, 6, 7, 8, 9])

In [45]:
nparray[nparray>6]

array([7, 8, 9])

In [46]:
nparray = np.arange(0,10)

In [47]:
#Operation
nparray + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
nparray *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
nparray + nparray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
nparray - nparray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
nparray / nparray

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [52]:
1/0

ZeroDivisionError: ignored

In [53]:
10/nparray

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf, 10.        ,  5.        ,  3.33333333,  2.5       ,
        2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111])

In [54]:
np.sin(nparray)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [55]:
np.log(nparray)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [56]:
nparray.sum()

45

In [57]:
nparray.var()

8.25

In [59]:
nparray.std()

2.8722813232690143

In [60]:
nparray = np.arange(0,25).reshape(5,5)
nparray.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [61]:
nparray.sum(axis=0)

array([50, 55, 60, 65, 70])